-- Copy of Core V4 products table; replace with the Core migration once CORE-003 (#12) merges.

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT NOT NULL REFERENCES shops(id) ON DELETE RESTRICT,
    name VARCHAR(255) NOT NULL,
    barcode VARCHAR(100),
    image_url VARCHAR(1000),
    unit VARCHAR(50) NOT NULL,
    selling_price_vnd BIGINT NOT NULL,
    cost_price_vnd BIGINT,
    tracked BOOLEAN NOT NULL DEFAULT FALSE,
    stock_quantity NUMERIC(15,3),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    archived_at TIMESTAMPTZ,
    archived_by_user_id BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_products_shop_barcode UNIQUE(shop_id, barcode),
    CONSTRAINT ck_products_status CHECK (status IN ('ACTIVE', 'ARCHIVED')),
    CONSTRAINT ck_products_prices CHECK (selling_price_vnd >= 0 AND (cost_price_vnd IS NULL OR cost_price_vnd >= 0)),
    CONSTRAINT ck_products_stock CHECK (
        (tracked AND stock_quantity IS NOT NULL AND stock_quantity >= 0)
        OR (NOT tracked AND stock_quantity IS NULL)
    ),
    CONSTRAINT ck_products_archive CHECK (
        (status = 'ARCHIVED' AND archived_at IS NOT NULL AND archived_by_user_id IS NOT NULL)
        OR (status = 'ACTIVE' AND archived_at IS NULL AND archived_by_user_id IS NULL)
    )
);
CREATE INDEX idx_products_shop_status ON products(shop_id, status);
