-- Forward-only audit schema. Preserve compatible Hibernate-created local rows.
-- Existing invalid data fails validation and rolls the whole migration back;
-- correct reviewed data before retrying, never erase or invent audit history.
-- Recovery after deployment: roll back application code while retaining logs,
-- then use a reviewed forward migration. Dropping this table is not a rollback.
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT NOT NULL,
    actor_role VARCHAR(20) NOT NULL,
    shop_id BIGINT NOT NULL,
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id BIGINT NOT NULL,
    outcome VARCHAR(20) NOT NULL,
    reason VARCHAR(500),
    request_id VARCHAR(36) NOT NULL,
    idempotency_key VARCHAR(255),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    old_data JSONB,
    new_data JSONB,
    ip_address VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Apply constraints outside CREATE TABLE so a table created by ddl-auto=update
-- receives the same protections without replacing its rows or identity sequence.
ALTER TABLE audit_logs
    ADD CONSTRAINT fk_audit_logs_actor
        FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_audit_logs_shop
        FOREIGN KEY (shop_id) REFERENCES shops(id) ON DELETE RESTRICT,
    ADD CONSTRAINT ck_audit_logs_ids
        CHECK (id > 0 AND actor_user_id > 0 AND shop_id > 0 AND entity_id > 0),
    ADD CONSTRAINT ck_audit_logs_actor_role CHECK (actor_role IN ('OWNER', 'ADMIN')),
    ADD CONSTRAINT ck_audit_logs_outcome CHECK (outcome = 'SUCCESS'),
    ADD CONSTRAINT ck_audit_logs_request_id
        CHECK (request_id ~ '^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$'),
    ADD CONSTRAINT ck_audit_logs_metadata CHECK (jsonb_typeof(metadata) = 'object'),
    ADD CONSTRAINT ck_audit_logs_action_target CHECK (
        (entity_type = 'SALE' AND action IN ('SALE_CONFIRMED', 'SALE_VOIDED'))
        OR (entity_type = 'SALE_REFUND' AND action = 'SALE_REFUND_RECORDED')
        OR (entity_type = 'DEBT' AND action IN ('DEBT_REPAYMENT_RECORDED', 'DEBT_VOIDED'))
        OR (entity_type = 'PRODUCT' AND action IN ('STOCK_ADJUSTED', 'STOCK_RESTORED_ON_VOID',
            'PRODUCT_CREATED', 'PRODUCT_UPDATED', 'PRODUCT_ARCHIVED'))
        OR (entity_type = 'EXPENSE' AND action IN ('EXPENSE_CREATED', 'EXPENSE_UPDATED', 'EXPENSE_ARCHIVED'))
        OR (entity_type = 'CATEGORY' AND action IN ('CATEGORY_CREATED', 'CATEGORY_UPDATED', 'CATEGORY_ARCHIVED'))
        OR (entity_type = 'SHOP' AND action IN ('SHOP_CREATED', 'SHOP_UPDATED', 'SHOP_ARCHIVED',
            'SHOP_INACTIVATED', 'SHOP_REACTIVATED'))
    );

CREATE INDEX IF NOT EXISTS idx_audit_logs_shop_time ON audit_logs(shop_id, created_at, id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON audit_logs(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_actor ON audit_logs(actor_user_id);

-- Row history is append-only, including bulk operations and zero-row attempts.
-- These guards do not replace separate application/migration DB roles: a schema
-- owner or superuser can disable triggers and must not be used by production API.
CREATE FUNCTION audit_logs_reject_mutation() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'Audit history is append-only' USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER trg_audit_logs_no_update_delete
    BEFORE UPDATE OR DELETE ON audit_logs
    FOR EACH STATEMENT EXECUTE FUNCTION audit_logs_reject_mutation();
CREATE TRIGGER trg_audit_logs_no_truncate
    BEFORE TRUNCATE ON audit_logs
    FOR EACH STATEMENT EXECUTE FUNCTION audit_logs_reject_mutation();
