-- Cloudinary media references and the post-commit cleanup outbox.
-- Existing rows deliberately remain NULL: Core never invents a provider asset for
-- a legacy URL. This migration is forward-only; recovery uses a later reviewed
-- migration, never edits to this file after it reaches a shared environment.
SET LOCAL lock_timeout = '5s';

ALTER TABLE products
    ADD COLUMN IF NOT EXISTS image_public_id VARCHAR(500);

ALTER TABLE shops
    ADD COLUMN IF NOT EXISTS logo_url VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS logo_public_id VARCHAR(500);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS avatar_public_id VARCHAR(500);

-- IF NOT EXISTS keeps a Hibernate ddl-auto=update local database adoptable.
-- Constraints below still validate all pre-existing rows and fail atomically on
-- invalid data rather than repairing or deleting media history.
CREATE TABLE IF NOT EXISTS media_cleanup_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(500) NOT NULL,
    asset_type VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL,
    attempt_count INTEGER NOT NULL,
    next_attempt_at TIMESTAMPTZ NOT NULL,
    last_error VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ
);

ALTER TABLE media_cleanup_jobs
    ADD CONSTRAINT ck_media_cleanup_jobs_asset_type
        CHECK (asset_type IN ('PRODUCT_IMAGE', 'SHOP_LOGO', 'USER_AVATAR')),
    ADD CONSTRAINT ck_media_cleanup_jobs_status
        CHECK (status IN ('PENDING', 'COMPLETED')),
    ADD CONSTRAINT ck_media_cleanup_jobs_attempt_count
        CHECK (attempt_count >= 0),
    ADD CONSTRAINT ck_media_cleanup_jobs_completion
        CHECK (
            (status = 'PENDING' AND completed_at IS NULL)
            OR (status = 'COMPLETED' AND completed_at IS NOT NULL)
        );

CREATE INDEX IF NOT EXISTS idx_media_cleanup_jobs_due
    ON media_cleanup_jobs (status, next_attempt_at, id);

-- V11's whitelist predates the user-scoped avatar audit. Product and shop media
-- continue to use their existing PRODUCT_UPDATED and SHOP_UPDATED actions.
-- Avatar changes are scoped to their actor, carry no shop/key/reason, and remain
-- append-only through the existing V10 triggers.
ALTER TABLE audit_logs DROP CONSTRAINT IF EXISTS ck_audit_logs_action_target;
ALTER TABLE audit_logs ADD CONSTRAINT ck_audit_logs_action_target CHECK (
    (shop_id IS NOT NULL AND entity_id IS NOT NULL AND (
        (entity_type = 'SALE' AND action IN ('SALE_CONFIRMED', 'SALE_VOIDED'))
        OR (entity_type = 'SALE_REFUND' AND action = 'SALE_REFUND_RECORDED')
        OR (entity_type = 'DEBT' AND action IN ('DEBT_REPAYMENT_RECORDED', 'DEBT_VOIDED'))
        OR (entity_type = 'PRODUCT' AND action IN ('STOCK_ADJUSTED', 'STOCK_RESTORED_ON_VOID',
            'PRODUCT_CREATED', 'PRODUCT_UPDATED', 'PRODUCT_ARCHIVED'))
        OR (entity_type = 'EXPENSE' AND action IN ('EXPENSE_CREATED', 'EXPENSE_UPDATED', 'EXPENSE_ARCHIVED'))
        OR (entity_type = 'CATEGORY' AND action IN ('CATEGORY_CREATED', 'CATEGORY_UPDATED', 'CATEGORY_ARCHIVED'))
        OR (entity_type = 'SHOP' AND action IN ('SHOP_CREATED', 'SHOP_UPDATED', 'SHOP_ARCHIVED',
            'SHOP_INACTIVATED', 'SHOP_REACTIVATED'))
    ))
    OR (action = 'USER_AVATAR_UPDATED' AND entity_type = 'USER'
        AND shop_id IS NULL AND entity_id = actor_user_id
        AND reason IS NULL AND idempotency_key IS NULL)
    OR (actor_role = 'ADMIN' AND reason IS NULL AND idempotency_key IS NULL AND (
        (action IN ('ADMIN_SHOP_VIEWED', 'ADMIN_SHOP_STATUS_HISTORY_VIEWED')
            AND entity_type = 'SHOP' AND shop_id IS NOT NULL AND entity_id IS NOT NULL AND entity_id = shop_id)
        OR (action = 'ADMIN_OWNER_VIEWED' AND entity_type = 'OWNER' AND shop_id IS NULL AND entity_id IS NOT NULL)
        OR (action = 'ADMIN_OVERVIEW_VIEWED' AND entity_type = 'SYSTEM' AND shop_id IS NULL AND entity_id IS NULL)
        OR (action = 'ADMIN_OWNERS_SEARCHED' AND entity_type = 'OWNER_LIST' AND shop_id IS NULL AND entity_id IS NULL)
        OR (action = 'ADMIN_SHOPS_SEARCHED' AND entity_type = 'SHOP_LIST' AND shop_id IS NULL AND entity_id IS NULL)
        OR (action = 'ADMIN_ACCESS_LOGS_VIEWED' AND entity_type = 'ADMIN_ACCESS_LOG_LIST' AND shop_id IS NULL AND entity_id IS NULL)
    ))
);
