-- Forward-only: V13 is already published for review. Recovery uses a new migration.
SET LOCAL lock_timeout = '5s';

CREATE TABLE IF NOT EXISTS media_upload_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_key VARCHAR(100) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    operation VARCHAR(100) NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    request_hash VARCHAR(128) NOT NULL,
    public_id VARCHAR(500) NOT NULL,
    lease_token UUID NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    response_body JSONB,
    CONSTRAINT uq_media_upload_scope_operation_key UNIQUE(scope_key, operation, idempotency_key)
);
CREATE INDEX IF NOT EXISTS idx_media_upload_public_id ON media_upload_keys(public_id);
