-- Forward-only expansion. No historical notifications or thresholds are invented.
-- Recovery: roll back the application with these additive structures retained;
-- corrections to shared databases require a new reviewed forward migration.
SET LOCAL lock_timeout = '5s';

ALTER TABLE products ADD COLUMN IF NOT EXISTS low_stock_threshold NUMERIC(15,3);
ALTER TABLE products ADD CONSTRAINT ck_products_low_stock_threshold
    CHECK (low_stock_threshold IS NULL OR low_stock_threshold >= 0);

-- IF NOT EXISTS permits adoption of a local Hibernate-created schema. Existing
-- rows are validated, never repaired/deleted. Stop writes during adoption/index
-- creation; these ordinary indexes are intended for new/small notification tables.
CREATE TABLE IF NOT EXISTS notification_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    body VARCHAR(1000) NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id BIGINT NOT NULL,
    data_json JSONB,
    dedup_key VARCHAR(255) NOT NULL,
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE notification_events
    ADD CONSTRAINT fk_notification_event_shop FOREIGN KEY (shop_id) REFERENCES shops(id) ON DELETE RESTRICT,
    ADD CONSTRAINT ck_notification_event_type CHECK (type IN
        ('LOW_STOCK', 'OUT_OF_STOCK', 'SALE_VOIDED', 'SHOP_INACTIVATED', 'SHOP_REACTIVATED')),
    ADD CONSTRAINT ck_notification_event_target CHECK (entity_id > 0 AND (
        (type IN ('LOW_STOCK', 'OUT_OF_STOCK') AND entity_type = 'PRODUCT')
        OR (type = 'SALE_VOIDED' AND entity_type = 'SALE' AND resolved_at IS NULL)
        OR (type IN ('SHOP_INACTIVATED', 'SHOP_REACTIVATED') AND entity_type = 'SHOP'
            AND entity_id = shop_id AND resolved_at IS NULL))),
    ADD CONSTRAINT ck_notification_event_resolution CHECK (resolved_at IS NULL OR resolved_at >= created_at),
    ADD CONSTRAINT ck_notification_event_data CHECK (data_json IS NULL OR jsonb_typeof(data_json) = 'object');

CREATE TABLE IF NOT EXISTS notification_recipients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_event_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE notification_recipients
    ADD CONSTRAINT fk_notification_recipient_event FOREIGN KEY (notification_event_id)
        REFERENCES notification_events(id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_notification_recipient_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
    ADD CONSTRAINT ck_notification_recipient_read CHECK (read_at IS NULL OR read_at >= created_at);

-- Hibernate may already have created these named UNIQUE constraints locally.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'notification_events'::regclass
        AND conname = 'uq_notification_event_dedup') THEN
        ALTER TABLE notification_events ADD CONSTRAINT uq_notification_event_dedup UNIQUE (shop_id, dedup_key);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'notification_recipients'::regclass
        AND conname = 'uq_notification_recipient') THEN
        ALTER TABLE notification_recipients ADD CONSTRAINT uq_notification_recipient
            UNIQUE (notification_event_id, user_id);
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_notification_open_stock
    ON notification_events (shop_id, entity_type, entity_id)
    WHERE type IN ('LOW_STOCK', 'OUT_OF_STOCK') AND resolved_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_notification_shop_time ON notification_events (shop_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_notification_recipient_time ON notification_recipients (user_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_notification_recipient_read ON notification_recipients (user_id, read_at);
