-- Customer directory and per-sale debt ledger (BR-008/009/010, FR-014/016, AC-006).
-- IF NOT EXISTS preserves local test rows when Hibernate update created these
-- two tables before Flyway was re-enabled. Constraints below still validate them.

CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    normalized_phone VARCHAR(30),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    archived_at TIMESTAMPTZ,
    archived_by_user_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE customers ADD CONSTRAINT fk_customers_shop
    FOREIGN KEY (shop_id) REFERENCES shops(id) ON DELETE RESTRICT;
ALTER TABLE customers ADD CONSTRAINT fk_customers_archived_by_user
    FOREIGN KEY (archived_by_user_id) REFERENCES users(id) ON DELETE RESTRICT;
ALTER TABLE customers ADD CONSTRAINT ck_customers_status
    CHECK (status IN ('ACTIVE', 'ARCHIVED'));
ALTER TABLE customers ADD CONSTRAINT ck_customers_archive
    CHECK (
        (status = 'ACTIVE' AND archived_at IS NULL AND archived_by_user_id IS NULL)
        OR (status = 'ARCHIVED' AND archived_at IS NOT NULL AND archived_by_user_id IS NOT NULL)
    );

-- Names and phone numbers are deliberately not unique: two different people
-- can share either value. The customer ID is the stable identity.
CREATE INDEX IF NOT EXISTS idx_customers_shop_phone ON customers(shop_id, normalized_phone);
CREATE INDEX IF NOT EXISTS idx_customers_shop_status ON customers(shop_id, status);

CREATE TABLE IF NOT EXISTS debts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL,
    original_vnd BIGINT NOT NULL,
    outstanding_vnd BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    settled_at TIMESTAMPTZ
);

ALTER TABLE debts ADD CONSTRAINT fk_debts_sale
    FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE RESTRICT;
ALTER TABLE debts ADD CONSTRAINT fk_debts_customer
    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE RESTRICT;
ALTER TABLE debts ADD CONSTRAINT ck_debts_balance
    CHECK (original_vnd > 0 AND outstanding_vnd >= 0 AND outstanding_vnd <= original_vnd);
ALTER TABLE debts ADD CONSTRAINT ck_debts_lifecycle
    CHECK (
        (status = 'OPEN' AND outstanding_vnd > 0 AND settled_at IS NULL)
        OR (status = 'SETTLED' AND outstanding_vnd = 0 AND settled_at IS NOT NULL)
    );

CREATE INDEX IF NOT EXISTS idx_debts_customer_status ON debts(customer_id, status);
CREATE INDEX IF NOT EXISTS idx_debts_status ON debts(status);

-- V4 left these references nullable until the customer and debt tables existed.
ALTER TABLE sale_drafts ADD CONSTRAINT fk_sale_drafts_customer
    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE RESTRICT;
ALTER TABLE sales ADD CONSTRAINT fk_sales_customer
    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE RESTRICT;
ALTER TABLE sales ADD CONSTRAINT ck_sales_debt_requires_customer
    CHECK (payment_status = 'PAID' OR customer_id IS NOT NULL);
ALTER TABLE payments ADD CONSTRAINT fk_payments_debt
    FOREIGN KEY (debt_id) REFERENCES debts(id) ON DELETE RESTRICT;
