-- Operating expenses belong to a shop and its OWNER (BR-008/009, FR-015).
-- IF NOT EXISTS preserves local rows created earlier by Hibernate ddl-auto=update.
CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    category VARCHAR(150),
    description VARCHAR(500),
    amount_vnd BIGINT NOT NULL,
    payment_method VARCHAR(20),
    expense_at TIMESTAMPTZ NOT NULL,
    source_ai_request_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    archived_at TIMESTAMPTZ,
    archived_by_user_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE expenses ADD CONSTRAINT fk_expenses_shop
    FOREIGN KEY (shop_id) REFERENCES shops(id) ON DELETE RESTRICT;
ALTER TABLE expenses ADD CONSTRAINT fk_expenses_created_by_user
    FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT;
ALTER TABLE expenses ADD CONSTRAINT fk_expenses_archived_by_user
    FOREIGN KEY (archived_by_user_id) REFERENCES users(id) ON DELETE RESTRICT;
ALTER TABLE expenses ADD CONSTRAINT ck_expenses_amount
    CHECK (amount_vnd > 0);
ALTER TABLE expenses ADD CONSTRAINT ck_expenses_payment_method
    CHECK (payment_method IS NULL OR payment_method IN ('CASH', 'TRANSFER'));
ALTER TABLE expenses ADD CONSTRAINT ck_expenses_status
    CHECK (status IN ('ACTIVE', 'ARCHIVED'));
ALTER TABLE expenses ADD CONSTRAINT ck_expenses_archive
    CHECK (
        (status = 'ACTIVE' AND archived_at IS NULL AND archived_by_user_id IS NULL)
        OR (status = 'ARCHIVED' AND archived_at IS NOT NULL AND archived_by_user_id IS NOT NULL)
    );

CREATE INDEX IF NOT EXISTS idx_expenses_shop_expense_at ON expenses(shop_id, expense_at);
CREATE INDEX IF NOT EXISTS idx_expenses_shop_status ON expenses(shop_id, status);
CREATE INDEX IF NOT EXISTS idx_expenses_source_ai_request_id ON expenses(source_ai_request_id);

-- The AI request table is not in Core's migration chain yet; add its FK with
-- that table rather than referencing a relation that does not exist today.
