-- Persist the result of a completed write so retries cannot create another
-- expense or debt payment (BR-016, FR-015/016, AC-024).
-- The table may already exist in a local database used to test this feature.
CREATE TABLE IF NOT EXISTS api_idempotency_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    operation VARCHAR(100) NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    request_hash VARCHAR(128) NOT NULL,
    resource_type VARCHAR(100),
    resource_id BIGINT,
    response_status INTEGER,
    response_body JSONB,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_api_idempotency_shop
        FOREIGN KEY (shop_id) REFERENCES shops (id) ON DELETE RESTRICT,
    CONSTRAINT fk_api_idempotency_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT uq_api_idempotency_shop_operation_key
        UNIQUE (shop_id, operation, idempotency_key),
    CONSTRAINT ck_api_idempotency_expiry
        CHECK (expires_at > created_at)
);

CREATE INDEX IF NOT EXISTS idx_api_idempotency_expires_at
    ON api_idempotency_keys (expires_at);
