-- Forward-only schema change for full sale void/refund. Never delete payments
-- or reconstruct stock/debt history from today's product or sale state.
-- Recover a failed migration by correcting reviewed data and retrying; after
-- deployment, use another migration or a backup restore, not edits to V1-V9.

-- NULL means the historical stock deduction is unknown, not false.
ALTER TABLE sale_items ADD COLUMN IF NOT EXISTS stock_deducted BOOLEAN;

ALTER TABLE debts
    ADD COLUMN IF NOT EXISTS voided_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS cancelled_vnd BIGINT;

-- ddl-auto=update may have left Hibernate's old OPEN/SETTLED enum check locally.
-- The replacement lifecycle check below also restricts the allowed statuses.
ALTER TABLE debts DROP CONSTRAINT IF EXISTS debts_status_check;
ALTER TABLE debts DROP CONSTRAINT ck_debts_lifecycle;
ALTER TABLE debts ADD CONSTRAINT ck_debts_lifecycle CHECK (
    (status = 'OPEN' AND outstanding_vnd > 0 AND settled_at IS NULL
        AND voided_at IS NULL AND cancelled_vnd IS NULL)
    OR (status = 'SETTLED' AND outstanding_vnd = 0 AND settled_at IS NOT NULL
        AND voided_at IS NULL AND cancelled_vnd IS NULL)
    OR (status = 'VOIDED' AND outstanding_vnd = 0 AND settled_at IS NULL
        AND voided_at IS NOT NULL AND cancelled_vnd IS NOT NULL
        AND cancelled_vnd > 0 AND cancelled_vnd <= original_vnd)
);

-- Preserve a table/rows already created for local Hibernate testing. The new
-- constraints validate existing rows too; inconsistent data stops migration.
CREATE TABLE IF NOT EXISTS sale_refunds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL,
    amount_vnd BIGINT NOT NULL,
    refund_method VARCHAR(20) NOT NULL,
    transfer_reference VARCHAR(255),
    refunded_by_user_id BIGINT NOT NULL,
    refunded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE sale_refunds ADD CONSTRAINT fk_sale_refunds_sale
    FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE RESTRICT;
ALTER TABLE sale_refunds ADD CONSTRAINT fk_sale_refunds_user
    FOREIGN KEY (refunded_by_user_id) REFERENCES users(id) ON DELETE RESTRICT;
ALTER TABLE sale_refunds ADD CONSTRAINT ck_sale_refunds_amount CHECK (amount_vnd > 0);
ALTER TABLE sale_refunds ADD CONSTRAINT ck_sale_refunds_method
    CHECK (refund_method IN ('CASH', 'TRANSFER'));

-- Hibernate uses this same name, so keep its existing unique constraint.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'sale_refunds'::regclass AND conname = 'uq_sale_refunds_sale_id'
    ) THEN
        ALTER TABLE sale_refunds ADD CONSTRAINT uq_sale_refunds_sale_id UNIQUE (sale_id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_sale_refunds_refunded_at ON sale_refunds(refunded_at);
