from contextlib import contextmanager

import pytest
from sqlalchemy.dialects import postgresql
from tests.support import CORE_MIGRATIONS, REPO_ROOT

from src.drafts.catalog import (
    CatalogProduct,
    CatalogUnavailableError,
    ProductCatalogRepository,
)
from src.infra.postgre_db_client import PostgreDBClient


class FakeSession:
    """Records each statement as PostgreSQL SQL and its params; answers with `rows`."""

    def __init__(self, rows: list[tuple]) -> None:
        self.rows = rows
        self.executed: list[tuple[str, dict]] = []

    def execute(self, statement) -> list[tuple]:
        compiled = statement.compile(dialect=postgresql.dialect())
        self.executed.append((str(compiled), compiled.params))
        return self.rows


class FakePostgres:
    """Stands in for PostgreDBClient; records the SQL and params a repository sends."""

    def __init__(self, rows: list[tuple]) -> None:
        self.fake_session = FakeSession(rows)

    @contextmanager
    def session(self):
        yield self.fake_session


def test_list_active_products_maps_rows_and_keeps_the_shop_filter() -> None:
    postgres = FakePostgres([(12, "Cà phê sữa", "cup", 25000)])
    repository = ProductCatalogRepository(postgres)

    products = repository.list_active_products(7)

    assert products == [
        CatalogProduct(id=12, name="Cà phê sữa", unit="cup", selling_price_vnd=25000)
    ]
    (timeout_sql, timeout_params), (query, params) = postgres.fake_session.executed
    assert "set_config" in timeout_sql
    assert list(timeout_params.values()) == ["statement_timeout", "3000", True]
    assert "products.shop_id = %(shop_id_1)s" in query
    assert "products.status = %(status_1)s" in query
    assert "ORDER BY products.name, products.id" in query
    assert params == {"shop_id_1": 7, "status_1": "ACTIVE"}


def test_is_active_product_true_only_when_the_row_is_found() -> None:
    found = ProductCatalogRepository(FakePostgres([(1,)]))
    missing = ProductCatalogRepository(FakePostgres([]))

    assert found.is_active_product(7, 12) is True
    assert missing.is_active_product(7, 12) is False

    query, params = missing.postgres.fake_session.executed[-1]
    assert "products.shop_id = %(shop_id_1)s" in query
    assert "products.id = %(id_1)s" in query
    assert "products.status = %(status_1)s" in query
    assert params == {"shop_id_1": 7, "id_1": 12, "status_1": "ACTIVE"}


def test_missing_ids_fail_closed_without_querying() -> None:
    postgres = FakePostgres([(12, "Cà phê sữa", "cup", 25000)])
    repository = ProductCatalogRepository(postgres)

    assert repository.list_active_products(None) == []
    assert repository.is_active_product(None, 12) is False
    assert repository.is_active_product(7, None) is False

    assert postgres.fake_session.executed == []


@pytest.mark.parametrize(
    "postgres",
    [
        PostgreDBClient(None),
        # Nothing listens on port 1, so the connection is refused at once.
        PostgreDBClient("postgresql://reader@127.0.0.1:1/db"),
    ],
    ids=["unconfigured", "unreachable"],
)
def test_database_failures_become_catalog_unavailable(postgres) -> None:
    repository = ProductCatalogRepository(postgres)

    with pytest.raises(CatalogUnavailableError):
        repository.list_active_products(7)
    with pytest.raises(CatalogUnavailableError):
        repository.is_active_product(7, 12)


def test_timeout_must_be_positive() -> None:
    with pytest.raises(ValueError):
        ProductCatalogRepository(FakePostgres([]), timeout_ms=0)


def test_catalog_product_id_is_int_matching_the_core_bigint_contract() -> None:
    """#37: DraftView copies products.id, which is BIGINT in the ERD, not a UUID."""
    assert CatalogProduct.__dataclass_fields__["id"].type is int

    core_products = (
        CORE_MIGRATIONS / "V4__create_catalog_and_paid_sales.sql"
    ).read_text()
    assert "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in core_products

    contract = (REPO_ROOT / "docs/contracts/api-contracts.md").read_text()
    assert '"product_id": "uuid-or-null"' not in contract
    assert "`product_id` là `BIGINT`" in contract
