from contextlib import contextmanager

import pytest
from tests.support import CORE_MIGRATIONS, REPO_ROOT

from src.drafts.catalog import (
    CatalogProduct,
    CatalogUnavailableError,
    ProductCatalogRepository,
)


class FakeCursor:
    def __init__(self, rows: list[tuple]) -> None:
        self.rows = rows
        self.executed: list[tuple[str, tuple]] = []

    def execute(self, query: str, params: tuple | None = None) -> None:
        self.executed.append((query, params))

    def fetchall(self) -> list[tuple]:
        return self.rows

    def fetchone(self) -> tuple | None:
        return self.rows[0] if self.rows else None

    def __enter__(self) -> "FakeCursor":
        return self

    def __exit__(self, *exc) -> bool:
        return False


class FakeConnection:
    def __init__(self, cursor: FakeCursor) -> None:
        self._cursor = cursor

    def cursor(self) -> FakeCursor:
        return self._cursor


class FakePostgres:
    """Stands in for PostgreDBClient; records the SQL and params a repository sends."""

    def __init__(self, rows: list[tuple]) -> None:
        self.cursor = FakeCursor(rows)

    @contextmanager
    def transaction(self):
        yield FakeConnection(self.cursor)


class FailingPostgres:
    """A client whose connection is gone, as after a dropped database link."""

    @contextmanager
    def transaction(self):
        raise RuntimeError("postgres unavailable")
        yield  # pragma: no cover


def test_list_active_products_maps_rows_and_keeps_the_shop_filter() -> None:
    postgres = FakePostgres([(12, "Cà phê sữa", "cup", 25000)])
    repository = ProductCatalogRepository(postgres)

    products = repository.list_active_products(7)

    assert products == [
        CatalogProduct(id=12, name="Cà phê sữa", unit="cup", selling_price_vnd=25000)
    ]
    assert any("statement_timeout" in query for query, _ in postgres.cursor.executed)
    query, params = postgres.cursor.executed[-1]
    assert "shop_id = %s" in query
    assert "status = 'ACTIVE'" in query
    assert params == (7,)


def test_is_active_product_true_only_when_the_row_is_found() -> None:
    found = ProductCatalogRepository(FakePostgres([(1,)]))
    missing = ProductCatalogRepository(FakePostgres([]))

    assert found.is_active_product(7, 12) is True
    assert missing.is_active_product(7, 12) is False

    query, params = missing.postgres.cursor.executed[-1]
    assert "shop_id = %s" in query
    assert "id = %s" in query
    assert "status = 'ACTIVE'" in query
    assert params == (7, 12)


def test_missing_ids_fail_closed_without_querying() -> None:
    postgres = FakePostgres([(12, "Cà phê sữa", "cup", 25000)])
    repository = ProductCatalogRepository(postgres)

    assert repository.list_active_products(None) == []
    assert repository.is_active_product(None, 12) is False
    assert repository.is_active_product(7, None) is False

    assert postgres.cursor.executed == []


def test_database_failures_become_catalog_unavailable() -> None:
    repository = ProductCatalogRepository(FailingPostgres())

    with pytest.raises(CatalogUnavailableError):
        repository.list_active_products(7)
    with pytest.raises(CatalogUnavailableError):
        repository.is_active_product(7, 12)


def test_timeout_must_be_positive() -> None:
    with pytest.raises(ValueError):
        ProductCatalogRepository(FakePostgres([]), timeout_ms=0)


def test_catalog_product_id_is_int_matching_the_core_bigint_contract() -> None:
    """#37: DraftView copies products.id, which is BIGINT in the ERD, not a UUID."""
    assert CatalogProduct.__dataclass_fields__["id"].type is int

    core_products = (
        CORE_MIGRATIONS / "V4__create_catalog_and_paid_sales.sql"
    ).read_text()
    assert "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in core_products

    contract = (REPO_ROOT / "docs/contracts/api-contracts.md").read_text()
    assert '"product_id": "uuid-or-null"' not in contract
    assert "`product_id` là `BIGINT`" in contract
