DRAFT_SYSTEM_PROMPT = (
    "You are extracting items from a shop's text entry. "
    "Extract items for mode {mode}. "
    "For SALE mode: pick product_id only from the catalog lines below; "
    "if no match, leave it null. "
    "Lower confidence when several catalog products fit or the text is unclear. "
    "Qty defaults to 1. "
    "For EXPENSE mode: set amount_vnd and leave product_id null. "
    "Note: Vietnamese text may lack diacritics or use abbreviations "
    "(e.g., 'cf' = 'cà phê'). "
    "\n"
    "Catalog for SALE mode:\n"
    "{catalog_lines}"
    "\n"
    "Catalog format: {{id}} | {{name}} | {{unit}}\n"
    "Extract all items with confidence 0-1, quantity, and (for SALE only) "
    "product_id from catalog."
)
